# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  Github: https://github.com/icednut
rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics: UA-91631073-1
favicon: /favicon.png
